spring:
  application:
    name: user-crud-hexagonal
    
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hexdb}
    username: ${SPRING_DATASOURCE_USERNAME:hexuser}
    password: ${SPRING_DATASOURCE_PASSWORD:hexpass}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
    
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    
logging:
  level:
    root: INFO
    com.example.usercrud: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false
  packagesToScan: com.example.usercrud.infrastructure.adapter.in.web.controller
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always